# Generated by Django 4.1 on 2022-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0003_alter_note_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('WR', 'Want to read'), ('Reading', 'Reading'), ('RD', 'Read')], default='WR', max_length=100),
        ),
    ]
