# Generated by Django 4.1 on 2022-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_alter_track_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('Want to read', 'Want to read'), ('Reading', 'Reading'), ('Read', 'Read')], default='Want to read', max_length=100),
        ),
    ]
