# Generated by Django 4.1.1 on 2022-09-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0006_alter_note_book_alter_note_user_alter_track_book_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user'),
        ),
    ]
