genres = [
    "Adventure",
    "Art / Photography",
    "Biography",
    "Contemporary",
    "Cookbook",
    "Children's",
    "Crafts / Hobbies",
    "Development",
    "Dystopian",
    "Families & Relationships",
    "Fantasy",
    "Fiction",
    "Guide / How-to",
    "Health",
    "History",
    "Historical Fiction",
    "Horror",
    "Humor",
    "Memoir / Autobiography",
    "Motivational",
    "Mystery",
    "Non-Fiction",
    "Paranormal",
    "Poetry",
    "Religious",
    "Romance",
    "Self-help",
    "Science Fiction",
    "Thriller",
    "Travel",
    "True Crime",
    "Western",
]
